# Generated by Django 2.2 on 2019-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('release_date', models.DateField()),
                ('trailer', models.CharField(max_length=70)),
                ('genres', models.ManyToManyField(to='app.MovieGenre')),
            ],
        ),
    ]
