# Generated by Django 2.2 on 2019-04-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_collectedmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertPickMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExpertPicksCategory')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
            ],
        ),
    ]
