# Generated by Django 2.2 on 2019-04-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_expertpickmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedmovie',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app.User'),
        ),
    ]
