# Generated by Django 2.2.1 on 2019-05-07 15:57

import tmdbsimple as tmdb
from django.db import migrations

import config


def add_genres(apps, schema_editor):
    """
    Inserts available genres from TMDB into the database.
    """

    MovieGenre = apps.get_model('app', 'MovieGenre')
    tmdb.API_KEY = config.TMDB_API_KEY
    genres = tmdb.Genres().movie_list()

    for genre in genres['genres']:
        movie_genre = MovieGenre(id=genre['id'], name=genre['name'])
        movie_genre.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_auto_20190416_0022'),
    ]

    operations = [
        migrations.RunPython(add_genres)
    ]
