# Generated by Django 2.2.1 on 2019-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_20190507_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
