# Generated by Django 2.2.1 on 2019-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_auto_20190516_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
