# Generated by Django 2.2.1 on 2019-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0013_remove_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedmovie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
