# Generated by Django 2.2.1 on 2019-06-03 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0015_auto_20190530_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertpickscategory',
            options={'ordering': ['name']},
        ),
    ]
